(()=>{var d={xmlns:"http://www.w3.org/2000/svg",width:24,height:24,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor","stroke-width":2,"stroke-linecap":"round","stroke-linejoin":"round"};var s=["svg",d,[["path",{d:"M12 16v5"}],["path",{d:"M16 14v7"}],["path",{d:"M20 10v11"}],["path",{d:"m22 3-8.646 8.646a.5.5 0 0 1-.708 0L9.354 8.354a.5.5 0 0 0-.707 0L2 15"}],["path",{d:"M4 18v3"}],["path",{d:"M8 14v7"}]]];window.__ModuleLoader__.load({id:"dsh-livebench-rankings",factory:p=>{let f=p("react"),t="dsh-livebench-rankings",e,u;function l(){e&&(e.close(),e.remove(),e=null,u?.focus())}function m(r){if(e)return;u=r.currentTarget,e=document.createElement("dialog"),e.dataset.plugin=t,Object.assign(e.style,{padding:"0",border:"1px solid #dce5df",borderRadius:"8px",width:"min(1400px, calc(100vw - 24px))",height:"min(960px, calc(100dvh - 24px))",maxWidth:"none",maxHeight:"none",background:"#f6f8f8",overflow:"hidden"});let a=document.createElement("iframe");a.src="/dsh-livebench-rankings/",a.title="LiveBench AI \u80FD\u529B\u6392\u884C\u699C",Object.assign(a.style,{width:"100%",height:"100%",display:"block",border:"0"}),e.append(a),e.addEventListener("cancel",o=>{o.preventDefault(),l()}),document.body.append(e),e.showModal()}function x(){return f.createElement("button",{type:"button",title:"LiveBench AI \u80FD\u529B\u6392\u884C\u699C","aria-label":"\u6253\u5F00 LiveBench AI \u80FD\u529B\u6392\u884C\u699C",onClick:m,style:{display:"inline-flex",alignItems:"center",gap:"5px",padding:"4px 8px",border:"1px solid var(--dsw-alias-border-l1, #cbd8d1)",borderRadius:"6px",fontSize:"12px",background:"transparent",color:"var(--dsw-alias-label-secondary, #627568)",cursor:"pointer",minHeight:"28px"}},f.createElement("svg",{width:15,height:15,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.7,"aria-hidden":!0},...s[2].map(([r,a],o)=>f.createElement(r,{...a,key:o}))),"AI \u6392\u884C")}return{name:t,inject:["slots"],apply(r){r.slots.inject("conversation.input.left",()=>r.slots.register({name:"conversation.input.left",id:t,order:95,label:()=>"LiveBench"},x)),r.effect(()=>{let a=o=>{o.origin===location.origin&&o.source===e?.querySelector("iframe")?.contentWindow&&o.data?.type===`${t}:close`&&l()};return window.addEventListener("message",a),()=>{window.removeEventListener("message",a),l()}},`${t}: isolated dialog`)}}}});})();
/*! Bundled license information:

lucide/dist/esm/defaultAttributes.js:
lucide/dist/esm/icons/chart-no-axes-combined.js:
lucide/dist/esm/lucide.js:
  (**
   * @license lucide v0.468.0 - ISC
   *
   * This source code is licensed under the ISC license.
   * See the LICENSE file in the root directory of this source tree.
   *)
*/
